"""The vessel mark, in dots, for the terminal the guided session opens in.

``anast`` typed bare on a terminal opens with one identity moment, and until
now it was a half-block and a word. This module draws the actual mark there:
the grid in :mod:`anastomosis.core.vesselmark_data` — the product logo sampled
cell by cell, generated by ``tools/make_vessel.py`` from the same geometry the
icon pipeline renders — laid down as dots beside the greeting, with a short
entrance that fills it from the trunk outward the way the vessel it draws
fills.

Three decisions carry the rest of the file:

* **The gradient is density and weight, never a colour.** §11 of
  ``docs/design/DESIGN_LANGUAGE.md`` holds for the mark as it holds for text:
  the background belongs to whoever is running this, so the CLI names nothing
  absolute. The ramp climbs the palette's own three weights (``dim``,
  ``default``, ``bold``) and one step in glyph size, both in the same
  direction, so the mark reads the same where a terminal renders neither.
* **The entrance is unreachable without a person watching it.** A pipe, a
  redirect or a CI runner never reaches this module (the guide itself refuses
  to run there), and :func:`can_draw` asks the output stream directly a second
  time — the same question, and for the same reason, as
  ``guide.is_interactive_terminal``.
* **No clock inside a frame.** :func:`frame_levels` takes a frame index and
  nothing else, so a test drives the entrance through exactly the states a
  terminal does. Time appears once, in :func:`_play`, which owns the sleeping
  and the keyboard.
"""

from __future__ import annotations

import math
import os
import sys
from contextlib import contextmanager
from typing import TYPE_CHECKING

from rich.text import Text

from anastomosis.core.presentation import (
    BRAND_PALETTE,
    UNICODE_GLYPHS,
    attached_to_a_terminal,
    terminal_glyphs,
)
from anastomosis.core.vesselmark_data import DENSITY, LEVELS

if TYPE_CHECKING:
    from collections.abc import Iterator, Sequence

    from rich.console import Console

__all__ = [
    "FRAMES",
    "MARK_HEIGHT",
    "MARK_WIDTH",
    "beside",
    "can_draw",
    "frame_levels",
    "mark_levels",
    "render",
    "show_greeting",
]

MARK_WIDTH = len(DENSITY[0])
MARK_HEIGHT = len(DENSITY)

#: Blank columns between the mark and the greeting beside it — the design
#: language's 8 px step, in the unit a terminal actually has.
GUTTER = 2
#: The narrowest column of text worth putting beside the mark. Under this the
#: greeting would wrap into two words a line, so the mark stands down instead
#: and the plain header (which wraps gracefully) is printed.
MIN_TEXT_COLUMNS = 24

#: The entrance, in frames and seconds per frame. Under a second in total: an
#: identity moment that outlasts the eye's patience is a delay, not a greeting.
FRAMES = 14
FRAME_SECONDS = 0.07

#: How much of the entrance is spent arriving rather than filling. Every cell
#: begins somewhere in the first 70 % of the run and takes the remaining 30 %
#: to reach full density, which is what makes the last frame — and only the
#: last frame — identical to the settled mark.
_SPREAD = 0.7

#: Level -> the palette weight that carries it. Three weights, and the mark
#: uses all three: the capillary rim is the supporting register, the body is
#: ordinary ink, and the trunk and hub are identity. No hue anywhere, because
#: ``red`` is this product's refusal colour and identity may not borrow it.
_WEIGHTS = (
    "",
    BRAND_PALETTE.ink_muted,
    BRAND_PALETTE.ink,
    BRAND_PALETTE.ink,
    BRAND_PALETTE.brand_bright,
)

#: Level -> glyph, on a stream that can carry them. Levels 1 and 2 share a
#: glyph and differ by weight; 3 and 4 step the glyph up as well, so density
#: and weight never disagree about which cell is heavier.
UNICODE_DOTS = (" ", "·", "·", "•", "●")
#: The same ramp for a console that cannot encode those — a legacy Windows
#: code page, a stream with no declared encoding. Pure ASCII, same shape.
ASCII_DOTS = (" ", ".", ".", "o", "O")

if not len(UNICODE_DOTS) == len(ASCII_DOTS) == len(_WEIGHTS) == LEVELS + 1:
    # The grid is generated and the ramp is written by hand; a regeneration
    # that changes how many levels a cell can carry has to be answered here.
    # Loudly, at import: a ramp one step short draws the densest cells as
    # whatever the last entry happens to be, which looks like a design.
    raise ValueError(
        f"the density ramp does not cover the mark: {LEVELS} levels sampled, "
        f"{len(UNICODE_DOTS) - 1} in the ramp"
    )


def mark_levels() -> tuple[tuple[int, ...], ...]:
    """The settled mark: every cell at the density the logo gives it."""
    return tuple(tuple(int(digit) for digit in row) for row in DENSITY)


def _entrance_offsets() -> tuple[tuple[float, ...], ...]:
    """When each cell starts arriving, as a fraction of the entrance.

    Distance from the foot of the trunk, scaled into ``[0, _SPREAD]``: the
    mark perfuses rather than fades in. Rows count double because a character
    cell is about twice as tall as it is wide, so the wave stays round.

    Scaled against the furthest cell the mark actually reaches, not the
    furthest corner of the grid: an empty corner setting the scale would let
    every inked cell finish early, and the entrance would sit on the settled
    mark for its last few frames instead of arriving at it.
    """
    levels = mark_levels()
    root_row = MARK_HEIGHT - 1
    root_col = max(range(MARK_WIDTH), key=lambda col: levels[root_row][col])
    spans = [
        [math.hypot(col - root_col, 2.0 * (root_row - row)) for col in range(MARK_WIDTH)]
        for row in range(MARK_HEIGHT)
    ]
    inked = [
        span
        for row, cells in zip(spans, levels, strict=True)
        for span, level in zip(row, cells, strict=True)
        if level
    ]
    longest = max(inked) or 1.0
    return tuple(tuple(min(span, longest) / longest * _SPREAD for span in row) for row in spans)


_OFFSETS = _entrance_offsets()


def frame_levels(frame: int) -> tuple[tuple[int, ...], ...]:
    """The density grid for one frame of the entrance.

    ``frame`` is the only input — there is no clock in here, which is what
    lets a test walk the entrance frame by frame and assert that it only ever
    gains ink. Frame ``FRAMES - 1`` is the settled mark exactly, and any
    frame past it stays there.
    """
    if frame < 0:
        raise ValueError(f"frame index must not be negative: {frame}")
    progress = min(1.0, (frame + 1) / FRAMES)
    grid = []
    for row, offsets in zip(mark_levels(), _OFFSETS, strict=True):
        arrived = ((progress - offset) / (1.0 - _SPREAD) for offset in offsets)
        grid.append(
            tuple(
                0 if share <= 0.0 else min(level, math.ceil(level * min(share, 1.0)))
                for level, share in zip(row, arrived, strict=True)
            )
        )
    return tuple(grid)


def render(levels: Sequence[Sequence[int]], *, unicode_dots: bool) -> list[Text]:
    """One :class:`~rich.text.Text` per row of the grid."""
    dots = UNICODE_DOTS if unicode_dots else ASCII_DOTS
    rows = []
    for row in levels:
        line = Text()
        for level in row:
            line.append(dots[level], style=_WEIGHTS[level] or None)
        rows.append(line)
    return rows


def beside(mark: Sequence[Text], lines: Sequence[Text]) -> list[Text]:
    """Compose the mark and the greeting into one block, mark on the left.

    The greeting sits against the middle of the mark rather than its top row:
    the mark is an object with a stem, and text hung off its crown reads as a
    caption that lost its picture. A greeting taller than the mark keeps going
    under it, in the same column, rather than being cut off at the last row of
    dots.
    """
    top = max(0, (len(mark) - len(lines)) // 2)
    composed = []
    for index in range(max(len(mark), top + len(lines))):
        line = mark[index].copy() if index < len(mark) else Text(" " * MARK_WIDTH)
        if top <= index < top + len(lines):
            line.append(" " * GUTTER)
            line.append(lines[index - top])
        line.rstrip()
        composed.append(line)
    return composed


def can_draw(console: Console) -> bool:
    """Whether this console gets the mark at all.

    Two refusals. A stream that is not really a terminal — a pipe, a redirect,
    a CI log — gets the plain header the CLI has always printed, and asking
    the stream itself (never anything that reports colour capability) is the
    same guard, for the same reason, as ``guide.is_interactive_terminal``. A
    console too narrow to hold the mark and a readable column of text beside
    it gets the plain header too, because a greeting wrapped into the dots is
    worse than no dots.
    """
    if not attached_to_a_terminal(getattr(console, "file", None)):
        return False
    return console.width >= MARK_WIDTH + GUTTER + MIN_TEXT_COLUMNS


def _motion_wanted(console: Console) -> bool:
    """Whether the mark may assemble rather than simply appear.

    ``NO_COLOR`` is honoured as a request for unadorned output, not only for
    an uncoloured one: whoever set it is reading this through something that
    keeps the bytes, and an entrance leaves a dozen half-drawn marks in a
    transcript where a settled one leaves the mark. A console Rich itself does
    not consider a terminal (``TERM=dumb``, and anything that cannot take a
    cursor movement) is drawn once, settled, for the same reason.
    """
    return console.is_terminal and not os.environ.get("NO_COLOR")


def show_greeting(console: Console, lines: Sequence[Text], *, animate: bool = True) -> bool:
    """Draw the mark with ``lines`` beside it. ``False`` means it stood down.

    The caller owns the words — every sentence this product says to an
    operator lives with the flow that says it — and this owns the object they
    are printed against.
    """
    if not can_draw(console):
        return False
    # The glyph set IS the capability decision, and the CLI already makes it in
    # one place: a UTF-8 stream gets the round dots, anything else (a CP-1252
    # console, a stream with no declared encoding) gets the ASCII ramp rather
    # than a line of replacement characters.
    unicode_dots = terminal_glyphs(console.file) is UNICODE_GLYPHS
    wrapped = _wrapped(console, lines)
    if animate and _motion_wanted(console):
        _play(console, wrapped, unicode_dots=unicode_dots)
    else:
        for line in beside(render(mark_levels(), unicode_dots=unicode_dots), wrapped):
            console.print(line)
    return True


def _wrapped(console: Console, lines: Sequence[Text]) -> list[Text]:
    """The greeting, folded to the column left over beside the mark.

    Rich would wrap it for us, but back to column zero — under the dots, where
    the second half of a sentence reads as a caption on the mark. Folding it
    here keeps the whole greeting in its own column.
    """
    column = console.width - MARK_WIDTH - GUTTER
    folded: list[Text] = []
    for line in lines:
        folded.extend(line.wrap(console, column))
    return folded


def _play(console: Console, lines: Sequence[Text], *, unicode_dots: bool) -> None:
    """Run the entrance once and leave the settled mark on screen.

    Bounded twice over: ``FRAMES`` frames is all there are, and the first
    keystroke ends it early. Whichever way it stops, the last thing written is
    the settled mark, so what an operator ends up looking at never depends on
    how long they were willing to watch.
    """
    import time

    from rich.console import Group
    from rich.live import Live

    def block(levels: Sequence[Sequence[int]]) -> Group:
        return Group(*beside(render(levels, unicode_dots=unicode_dots), lines))

    with _single_keystrokes(), Live(console=console, auto_refresh=False) as live:
        for frame in range(FRAMES - 1):
            live.update(block(frame_levels(frame)), refresh=True)
            time.sleep(FRAME_SECONDS)
            if _key_pressed():
                break
        live.update(block(mark_levels()), refresh=True)


@contextmanager
def _single_keystrokes() -> Iterator[None]:
    """Ask the terminal to hand over keys as they are typed, for the entrance.

    Interrupting on a keypress needs the keypress before the Enter that would
    normally deliver it. Ctrl-C still interrupts, because cbreak leaves signal
    generation on. A terminal that will not take the mode change — no
    ``termios``, a stdin that is not a file — simply plays the entrance out,
    which is under a second either way.
    """
    if sys.platform == "win32":  # pragma: no cover - windows reads keys unbuffered
        yield
        return
    import termios
    import tty

    try:
        descriptor = sys.stdin.fileno()
        saved = termios.tcgetattr(descriptor)
    except (AttributeError, OSError, ValueError):
        yield
        return
    tty.setcbreak(descriptor)
    try:
        yield
    finally:
        termios.tcsetattr(descriptor, termios.TCSADRAIN, saved)


def _key_pressed() -> bool:
    """Whether a key has been hit — and if so, swallow what was typed.

    Swallowed on purpose: the keystroke that ended the entrance was aimed at
    the entrance, and letting it fall through would answer the menu question
    printed a moment later with a character nobody chose.
    """
    if sys.platform == "win32":  # pragma: no cover - exercised on the windows leg
        import msvcrt

        pressed = False
        while msvcrt.kbhit():
            msvcrt.getwch()
            pressed = True
        return pressed
    import select

    try:
        ready, _writable, _failed = select.select([sys.stdin], [], [], 0)
        if not ready:
            return False
        os.read(sys.stdin.fileno(), 4096)
    except (AttributeError, OSError, ValueError):
        return False
    return True
