"""The vessel mark, in dots, for the terminal the guided session opens in.

``anast`` typed bare on a terminal opens with one identity moment, and until
now it was a half-block and a word. This module draws the actual mark there:
the grid in :mod:`anastomosis.core.vesselmark_data` — the product logo sampled
cell by cell, generated by ``tools/make_vessel.py`` from the same geometry the
icon pipeline renders — laid down as dots beside the greeting, with a short
entrance that fills it from the trunk outward the way the vessel it draws
fills.

Three decisions carry the rest of the file:

* **The gradient is density and weight, never a colour.** §11 of
  ``docs/design/DESIGN_LANGUAGE.md`` holds for the mark as it holds for text:
  the background belongs to whoever is running this, so the CLI names nothing
  absolute. The ramp climbs the palette's own three weights (``dim``,
  ``default``, ``bold``) and one step in glyph size, both in the same
  direction, so the mark reads the same where a terminal renders neither.
* **The entrance is unreachable without a person watching it.** A pipe, a
  redirect or a CI runner never reaches this module (the guide itself refuses
  to run there), and :func:`can_draw` asks the output stream directly a second
  time — the same question, and for the same reason, as
  ``guide.is_interactive_terminal``.
* **No clock inside a frame.** :func:`frame_levels` takes a frame index and
  nothing else, so a test drives the entrance through exactly the states a
  terminal does. Time appears once, in :func:`_play`, which owns the sleeping
  and the keyboard.
"""

from __future__ import annotations

import math
import os
import sys
from contextlib import contextmanager
from typing import IO, TYPE_CHECKING, Any, cast

from rich.text import Text

from anastomosis.core.presentation import (
    BRAND_PALETTE,
    UNICODE_GLYPHS,
    attached_to_a_terminal,
    terminal_colour_depth,
    terminal_glyphs,
)
from anastomosis.core.vesselmark_data import DENSITY, LEVELS

if TYPE_CHECKING:
    from collections.abc import Iterator, Sequence

    from rich.console import Console

__all__ = [
    "FRAMES",
    "MARK_HEIGHT",
    "MARK_STOPS",
    "MARK_STOPS_256",
    "MARK_WIDTH",
    "beside",
    "can_draw",
    "frame_levels",
    "home_stops",
    "mark_levels",
    "pulse_frame",
    "render",
    "show_greeting",
    "wave",
]

MARK_WIDTH = len(DENSITY[0])
MARK_HEIGHT = len(DENSITY)

#: Blank columns between the mark and the greeting beside it — the design
#: language's 8 px step, in the unit a terminal actually has.
GUTTER = 2
#: The narrowest column of text worth putting beside the mark. Under this the
#: greeting would wrap into two words a line, so the mark stands down instead
#: and the plain header (which wraps gracefully) is printed.
MIN_TEXT_COLUMNS = 24

#: The entrance, in frames and seconds per frame. Under a second in total: an
#: identity moment that outlasts the eye's patience is a delay, not a greeting.
#: What follows the entrance is not bounded the same way — see :func:`_play`.
FRAMES = 14
FRAME_SECONDS = 0.05

#: How much of the entrance is spent arriving rather than filling. Every cell
#: begins somewhere in the first 70 % of the run and takes the remaining 30 %
#: to reach full density, which is what makes the last frame — and only the
#: last frame — identical to the settled mark.
_SPREAD = 0.7

#: Level -> the palette weight that carries it. Three weights, and the mark
#: uses all three: the capillary rim is the supporting register, the body is
#: ordinary ink, and the trunk and hub are identity. No hue anywhere, because
#: ``red`` is this product's refusal colour and identity may not borrow it.
_WEIGHTS = (
    "",
    BRAND_PALETTE.ink_muted,
    BRAND_PALETTE.ink,
    BRAND_PALETTE.ink,
    BRAND_PALETTE.brand_bright,
)

#: Level -> glyph: braille cells carrying 0, 2, 4, 6 and 8 dots. An area ramp,
#: horizontally symmetric, and every step a 33 % change rather than the 2x jump
#: the old level 3 -> 4 made — which is most of why the canopy stopped reading
#: as speckle. Braille also fixes a live bug: `·` U+00B7, `•` U+2022 and `●`
#: U+25CF are all East Asian Width Ambiguous and render DOUBLE WIDTH on any
#: terminal configured for CJK, shearing this 21-column grid. Every codepoint
#: in U+2800-U+28FF is Narrow.
#: Level 0 is a real space, NOT U+2800 BRAILLE PATTERN BLANK. The blank looks
#: identical and is not whitespace, so `beside`'s `rstrip` stops trimming and
#: every empty row ships 21 printing characters into somebody's scrollback.
UNICODE_DOTS = (" ", *(chr(0x2800 | bits) for bits in (0x12, 0x36, 0x3F, 0xFF)))
#: The same ramp for a console that cannot encode those — a legacy Windows
#: code page, a stream with no declared encoding. Pure ASCII, same shape, and
#: five distinct glyphs now that the braille ramp has five.
ASCII_DOTS = (" ", ".", ":", "o", "O")

#: The mark's ramp, and the ONLY absolute colour this program emits — §11 of
#: docs/design/DESIGN_LANGUAGE.md is amended for exactly this and nothing else.
#: Brand hue (OKLCh H=30, the icon's own measured 29.7) re-derived at terminal
#: luminance: every stop sits inside the 0.175-0.242 window where 3 : 1 holds on
#: a dark AND a light ground. The icon's own oxblood does not — `#701a14`
#: measures 1.23 : 1 on One Dark `#282c34`, which is why the palette could not
#: simply be reused. The gradient travels in chroma rather than lightness
#: because that window is only 0.067 wide, and because "more pigment" reads the
#: same direction on both grounds where "brighter" inverts.
MARK_STOPS: tuple[str, ...] = (
    "#7e7370",
    "#947069",
    "#a86a60",
    "#bc6658",
    "#cf5e4e",
    "#e35544",
)
#: The same ramp at 256 colours, as explicit indices rather than a downgrade:
#: rich memoises a Style's ANSI string on first render and reuses it at any
#: depth, so a hex asked for once can leak truecolor bytes to a 256-colour
#: console. An index is immune — it renders as 38;5;N everywhere. Only 27 of
#: the 240 non-ANSI entries clear 3 : 1 on all nine grounds, which collapses
#: six stops into three pairs; that mirrors the weight ramp, where
#: `_WEIGHTS[2] == _WEIGHTS[3]` already.
MARK_STOPS_256: tuple[str, ...] = (
    "color(243)",
    "color(243)",
    "color(131)",
    "color(131)",
    "color(167)",
    "color(167)",
)

if not len(UNICODE_DOTS) == len(ASCII_DOTS) == len(_WEIGHTS) == LEVELS + 1:
    # The grid is generated and the ramp is written by hand; a regeneration
    # that changes how many levels a cell can carry has to be answered here.
    # Loudly, at import: a ramp one step short draws the densest cells as
    # whatever the last entry happens to be, which looks like a design.
    raise ValueError(
        f"the density ramp does not cover the mark: {LEVELS} levels sampled, "
        f"{len(UNICODE_DOTS) - 1} in the ramp"
    )


def mark_levels() -> tuple[tuple[int, ...], ...]:
    """The settled mark: every cell at the density the logo gives it."""
    return tuple(tuple(int(digit) for digit in row) for row in DENSITY)


def _entrance_offsets() -> tuple[tuple[float, ...], ...]:
    """When each cell starts arriving, as a fraction of the entrance.

    Distance from the foot of the trunk, scaled into ``[0, _SPREAD]``: the
    mark perfuses rather than fades in. Rows count double because a character
    cell is about twice as tall as it is wide, so the wave stays round.

    Scaled against the furthest cell the mark actually reaches, not the
    furthest corner of the grid: an empty corner setting the scale would let
    every inked cell finish early, and the entrance would sit on the settled
    mark for its last few frames instead of arriving at it.
    """
    levels = mark_levels()
    root_row = MARK_HEIGHT - 1
    root_col = max(range(MARK_WIDTH), key=lambda col: levels[root_row][col])
    spans = [
        [math.hypot(col - root_col, 2.0 * (root_row - row)) for col in range(MARK_WIDTH)]
        for row in range(MARK_HEIGHT)
    ]
    inked = [
        span
        for row, cells in zip(spans, levels, strict=True)
        for span, level in zip(row, cells, strict=True)
        if level
    ]
    longest = max(inked) or 1.0
    return tuple(tuple(min(span, longest) / longest * _SPREAD for span in row) for row in spans)


_OFFSETS = _entrance_offsets()


def frame_levels(frame: int) -> tuple[tuple[int, ...], ...]:
    """The density grid for one frame of the entrance.

    ``frame`` is the only input — there is no clock in here, which is what
    lets a test walk the entrance frame by frame and assert that it only ever
    gains ink. Frame ``FRAMES - 1`` is the settled mark exactly, and any
    frame past it stays there.
    """
    if frame < 0:
        raise ValueError(f"frame index must not be negative: {frame}")
    progress = min(1.0, (frame + 1) / FRAMES)
    grid = []
    for row, offsets in zip(mark_levels(), _OFFSETS, strict=True):
        arrived = ((progress - offset) / (1.0 - _SPREAD) for offset in offsets)
        grid.append(
            tuple(
                0 if share <= 0.0 else min(level, math.ceil(level * min(share, 1.0)))
                for level, share in zip(row, arrived, strict=True)
            )
        )
    return tuple(grid)


#: A rectangle of per-cell integers — levels or stops, same shape either way.
_Grid = tuple[tuple[int, ...], ...]


# --- the perfusion field -----------------------------------------------------

#: The anastomosis hub — where the two cut vessels meet the trunk, which is the
#: thing this product is named for. Derived, not chosen: ``make_vessel.build``
#: puts it at (0.500, 0.615) of a 1024 canvas, cells are 1024/21 x 1024/11, and
#: ``sample_matrix`` trims one all-zero row off the top.
HUB_COL, HUB_ROW = 10.0, 5.265

#: Base pulse, in hertz, and the three temporal ratios riding it. The ratios
#: are INCOMMENSURABLE on purpose: 0.618 and 1.481 share no small-integer
#: relation with 1.0, so the superposition has no period and the mark never
#: repeats itself. That is the whole reason this can loop without looking like
#: a loop.
_F0 = 0.85
_RATIO = (1.000, 0.618, 1.481)
#: Spatial wavelengths, in the doubled-row world units distance is measured in.
#: Nyquist-bounded: rows sample every 2 units, so 6.1 gets 3.05 samples per
#: cycle vertically. Below about 5 it aliases into speckle; above R_MAX no
#: crest fits inside the mark at all.
_LAM = (9.0, 6.1, 13.7)
_AMP = (0.60, 0.28, 0.16)
#: The glyph gain floor. At the trough a cell keeps 55 % of its settled level,
#: which is what stops the outline flickering: levels 1 and 2 hold while 3 and
#: 4 breathe, so the capillary rim carries the silhouette steady.
_G0 = 0.55
#: Frames the amplitude takes to come up after the entrance, and the ceiling on
#: an unwatched greeting.
#:
#: The ceiling is a real cost of running continuously and it was measured, not
#: guessed: the pty test drives ``anast`` for real, and at a 1200-frame cap the
#: run never reached the menu inside sixty seconds. Nothing was broken — the
#: mark was perfusing exactly as designed, and the question underneath it was
#: waiting for the animation to finish. A greeting that holds the prompt is not
#: alive, it is in the way.
#:
#: So: any keystroke ends it instantly, and failing that eight seconds does.
#: Nobody ever sees it repeat, because the field has no period — eight seconds
#: is simply the longest this may make somebody wait who typed ``anast`` and
#: then looked away. Genuinely endless motion needs the mark to live UNDER the
#: prompt rather than before it, which needs the self-echoing reader in #330;
#: until that lands, this is where continuous honestly stops.
_RAMP_IN = 6
_IDLE_FRAMES = 160


def _phase_offset(col: int, row: int) -> float:
    """A smooth, lattice-free phase shift per cell.

    Two incommensurable plane waves rather than a hash of the coordinates:
    white noise looks like television static, and a smooth field looks like
    tissue. It also breaks the ring coherence that a pure radial term would
    otherwise give, which is what separates a pulse from a sonar ping.
    """
    u, v = float(col), 2.0 * row
    return 0.45 * (0.9 * math.sin(0.70 * u + 1.30 * v) + 0.6 * math.sin(-1.10 * u + 0.53 * v))


def wave(col: int, row: int, seconds: float, seed: float = 0.0) -> float:
    """The field at one cell at one instant, in ``[0, 1]``.

    The minus sign on time is what makes crests travel OUTWARD from the hub:
    holding phase constant requires distance to grow as time does. The
    smoothstep at the end turns a sine — which spends equal time in crest and
    trough, and reads as machinery — into fast attack and slow decay.

    ``seed`` shifts where in the endless field a run begins. Two people typing
    ``anast`` at the same moment see different marks, and nobody sees the same
    opening twice; the silhouette is identical every time because that is the
    logo, and the light moving through it never is.
    """
    distance = math.hypot(col - HUB_COL, 2.0 * (row - HUB_ROW))
    phase = _phase_offset(col, row)
    # The mark is mirror-symmetric about column 10 and distance therefore reads
    # identically on both cut vessels. Without this term both arms pulse in
    # lockstep, which is visibly mechanical. It has no seam at the hub.
    lateral = 0.15 * (col - HUB_COL)
    raw = 0.0
    for amp, lam, ratio in zip(_AMP, _LAM, _RATIO, strict=True):
        angle = math.tau * distance / lam - math.tau * _F0 * ratio * seconds
        raw += amp * math.sin(angle + phase * ratio + lateral + seed * ratio)
    unit = 0.5 + 0.5 * raw / 1.04
    return unit * unit * (3.0 - 2.0 * unit)


def _amplitude(frame: int) -> float:
    """How much of the field reaches the mark at ``frame``.

    Zero through the entrance — the wave's phase runs the whole time so it is
    continuous when it arrives, it simply has no reach yet — then smoothstepped
    up over ``_RAMP_IN`` frames and held. There is no settle STAGE any more:
    settling is an exit, taken when somebody presses a key.
    """
    if frame < FRAMES:
        return 0.0
    ramp = min(1.0, (frame - FRAMES + 1) / _RAMP_IN)
    return ramp * ramp * (3.0 - 2.0 * ramp)


def pulse_frame(frame: int, seed: float = 0.0) -> tuple[_Grid, _Grid]:
    """One frame of the perfusion, as ``(levels, stops)``.

    Two channels from one scalar, so the mark is complete with colour stripped:
    the glyph carries form and the stop carries light. At the settle target
    ``w = 0.5`` the gain is 0.775, and ``ceil(n * 0.775) == n`` for every n in
    1..4, while the stop delta is zero — so amplitude zero reproduces the
    settled mark EXACTLY in both channels, which is what the exit relies on.
    """
    seconds = frame * FRAME_SECONDS
    amplitude = _amplitude(frame)
    levels, stops = [], []
    for row, home_row in enumerate(mark_levels()):
        level_row, stop_row = [], []
        for col, home in enumerate(home_row):
            if home == 0:
                level_row.append(0)
                stop_row.append(0)
                continue
            unit = 0.5 + amplitude * (wave(col, row, seconds, seed) - 0.5)
            gain = _G0 + (1.0 - _G0) * unit
            level_row.append(max(1, min(home, math.ceil(home * gain))))
            delta = -1 if unit < 0.25 else (1 if unit > 0.75 else 0)
            stop_row.append(max(0, min(len(MARK_STOPS) - 1, home + delta)))
        levels.append(tuple(level_row))
        stops.append(tuple(stop_row))
    return tuple(levels), tuple(stops)


def home_stops() -> _Grid:
    """Every cell on the stop its density gives it — the settled colouring."""
    return mark_levels()


def render(
    levels: Sequence[Sequence[int]],
    *,
    unicode_dots: bool,
    stops: Sequence[Sequence[int]] | None = None,
    palette: Sequence[str] | None = None,
) -> list[Text]:
    """One :class:`~rich.text.Text` per row of the grid.

    With no ``stops`` and no ``palette`` this is what it has always been: glyph
    size and text weight, and not one absolute value. That is not a legacy path
    — it is what a sixteen-colour terminal, a ``NO_COLOR`` session and a
    redirected stream all still get, and the two channels are ordered the same
    way so the mark reads identically without either.
    """
    dots = UNICODE_DOTS if unicode_dots else ASCII_DOTS
    rows = []
    for index, row in enumerate(levels):
        line = Text()
        for column, level in enumerate(row):
            if level and stops is not None and palette is not None:
                style: str | None = palette[stops[index][column]]
            else:
                style = _WEIGHTS[level] or None
            line.append(dots[level], style=style)
        rows.append(line)
    return rows


def beside(mark: Sequence[Text], lines: Sequence[Text]) -> list[Text]:
    """Compose the mark and the greeting into one block, mark on the left.

    The greeting sits against the middle of the mark rather than its top row:
    the mark is an object with a stem, and text hung off its crown reads as a
    caption that lost its picture. A greeting taller than the mark keeps going
    under it, in the same column, rather than being cut off at the last row of
    dots.
    """
    top = max(0, (len(mark) - len(lines)) // 2)
    composed = []
    for index in range(max(len(mark), top + len(lines))):
        line = mark[index].copy() if index < len(mark) else Text(" " * MARK_WIDTH)
        if top <= index < top + len(lines):
            line.append(" " * GUTTER)
            line.append(lines[index - top])
        line.rstrip()
        composed.append(line)
    return composed


def can_draw(console: Console) -> bool:
    """Whether this console gets the mark at all.

    Two refusals. A stream that is not really a terminal — a pipe, a redirect,
    a CI log — gets the plain header the CLI has always printed, and asking
    the stream itself (never anything that reports colour capability) is the
    same guard, for the same reason, as ``guide.is_interactive_terminal``. A
    console too narrow to hold the mark and a readable column of text beside
    it gets the plain header too, because a greeting wrapped into the dots is
    worse than no dots.
    """
    if not attached_to_a_terminal(getattr(console, "file", None)):
        return False
    return console.width >= MARK_WIDTH + GUTTER + MIN_TEXT_COLUMNS


def _motion_wanted(console: Console) -> bool:
    """Whether the mark may assemble rather than simply appear.

    ``NO_COLOR`` is honoured as a request for unadorned output, not only for
    an uncoloured one: whoever set it is reading this through something that
    keeps the bytes, and an entrance leaves a dozen half-drawn marks in a
    transcript where a settled one leaves the mark. A console Rich itself does
    not consider a terminal (``TERM=dumb``, and anything that cannot take a
    cursor movement) is drawn once, settled, for the same reason.
    """
    return console.is_terminal and not os.environ.get("NO_COLOR")


def show_greeting(console: Console, lines: Sequence[Text], *, animate: bool = True) -> bool:
    """Draw the mark with ``lines`` beside it. ``False`` means it stood down.

    The caller owns the words — every sentence this product says to an
    operator lives with the flow that says it — and this owns the object they
    are printed against.
    """
    if not can_draw(console):
        return False
    # The glyph set IS the capability decision, and the CLI already makes it in
    # one place: a UTF-8 stream gets the round dots, anything else (a CP-1252
    # console, a stream with no declared encoding) gets the ASCII ramp rather
    # than a line of replacement characters.
    unicode_dots = terminal_glyphs(console.file) is UNICODE_GLYPHS
    wrapped = _wrapped(console, lines)
    if animate and _motion_wanted(console):
        _play(console, wrapped, unicode_dots=unicode_dots)
    else:
        for line in beside(render(mark_levels(), unicode_dots=unicode_dots), wrapped):
            console.print(line)
    return True


def _wrapped(console: Console, lines: Sequence[Text]) -> list[Text]:
    """The greeting, folded to the column left over beside the mark.

    Rich would wrap it for us, but back to column zero — under the dots, where
    the second half of a sentence reads as a caption on the mark. Folding it
    here keeps the whole greeting in its own column.
    """
    column = console.width - MARK_WIDTH - GUTTER
    folded: list[Text] = []
    for line in lines:
        folded.extend(line.wrap(console, column))
    return folded


def _play(console: Console, lines: Sequence[Text], *, unicode_dots: bool) -> None:
    """Run the greeting and leave the settled mark on screen.

    It does not play once and stop. The entrance arrives up the trunk, the
    perfusion takes over, and then it keeps going — the field's three temporal
    ratios are incommensurable, so nothing in it ever repeats and there is no
    loop to be caught looping. A per-run seed starts each invocation somewhere
    else in that field.

    Bounded twice, and neither bound is the animation running out of material.
    The first keystroke ends it, and is swallowed so it cannot answer the menu
    question printed a moment later. Failing that, ``_IDLE_FRAMES`` settles a
    terminal nobody came back to rather than spending 2.5 % of a core until the
    session ends. Whichever way it stops, the last thing written is the settled
    mark, so what an operator ends up looking at never depends on how long they
    were willing to watch.

    It must never run while a prompt is open. Verified in rich: ``Live`` hides
    the cursor, redirects stdout and stderr but NOT stdin, ``Console.input``
    has no coordination with it, and ``LiveRender.position_cursor`` erases each
    line before redrawing — so a question asked underneath this gives a blind
    cursor and characters wiped twenty times a second. Animate, settle, THEN
    ask.
    """
    import time

    from rich.console import Group
    from rich.live import Live

    # Orthogonal to the glyph set on purpose: a CP-1252 Windows Terminal draws
    # the ASCII ramp in 256 colours, and a UTF-8 xterm with NO_COLOR draws
    # braille in none. Encoding and colour depth are different questions.
    palette = _palette(console)
    seed = _seed()

    def block(levels: Sequence[Sequence[int]], stops: Sequence[Sequence[int]]) -> Group:
        drawn = render(levels, unicode_dots=unicode_dots, stops=stops, palette=palette)
        return Group(*beside(drawn, lines))

    original = console.file
    # rich types `console.file` as IO[str]; the wrapper forwards everything it
    # does not implement, and only `write` is on rich's hot path. The cast says
    # that out loud rather than widening the wrapper into a fake file object.
    #
    # NOT on a legacy Windows console. There, rich renders through
    # `legacy_windows_render` and a `LegacyWindowsTerm`, which colours by
    # calling the console API and passes the plain text down to
    # `console.file.write` — us. That console has no VT parser, so the two DEC
    # private sequences the wrapper adds are not ignored, they are PRINTED:
    # `<-[?2026h` at the head of every frame, twenty times a second. The
    # synchronisation is a nicety; the garbage would not be.
    if not console.legacy_windows:
        console.file = cast("IO[str]", _Synchronised(original))
    try:
        with _single_keystrokes(), Live(console=console, auto_refresh=False) as live:
            for frame in range(_IDLE_FRAMES):
                live.update(block(*_grid(frame, seed)), refresh=True)
                time.sleep(FRAME_SECONDS)
                if _key_pressed():
                    break
            live.update(block(mark_levels(), home_stops()), refresh=True)
    finally:
        console.file = original


def _grid(frame: int, seed: float) -> tuple[_Grid, _Grid]:
    """The entrance while it lasts, the perfusion after it."""
    if frame < FRAMES - 1:
        return frame_levels(frame), home_stops()
    return pulse_frame(frame, seed)


def _seed() -> float:
    """Where in the endless field this run begins."""
    import secrets

    return secrets.randbelow(10_000) / 10_000 * math.tau


def _palette(console: Console) -> tuple[str, ...] | None:
    """The stops this console can carry, or ``None`` for weight alone."""
    depth = terminal_colour_depth(console)
    if depth == "truecolor":
        return MARK_STOPS
    if depth == "256":
        return MARK_STOPS_256
    return None


class _Synchronised:
    """DECSET 2026 around each write: the terminal presents a frame atomically.

    The flicker in a ten-line erase-and-redraw at twenty frames a second is
    most of what separates "alive" from "broken", and rich has no support for
    the mode. Terminals that do not implement it ignore an unknown DEC private
    parameter, so this costs 19 bytes a frame and nothing else.

    Both halves go out in one call on purpose: tmux freezes a pane for up to a
    second when a begin is never matched by an end, and an exception between
    two separate writes would do exactly that.
    """

    def __init__(self, file: Any) -> None:
        self._file = file

    def write(self, text: str) -> int:
        if not text:
            return 0
        return int(self._file.write(f"\x1b[?2026h{text}\x1b[?2026l"))

    def __getattr__(self, name: str) -> Any:
        return getattr(self._file, name)


@contextmanager
def _single_keystrokes() -> Iterator[None]:
    """Ask the terminal to hand over keys as they are typed, for the entrance.

    Interrupting on a keypress needs the keypress before the Enter that would
    normally deliver it. Ctrl-C still interrupts, because cbreak leaves signal
    generation on. A terminal that will not take the mode change — no
    ``termios``, a stdin that is not a file — simply plays the entrance out,
    which is under a second either way.
    """
    if sys.platform == "win32":  # pragma: no cover - windows reads keys unbuffered
        yield
        return
    import termios
    import tty

    try:
        descriptor = sys.stdin.fileno()
        saved = termios.tcgetattr(descriptor)
    except (AttributeError, OSError, ValueError):
        yield
        return
    tty.setcbreak(descriptor)
    try:
        yield
    finally:
        termios.tcsetattr(descriptor, termios.TCSADRAIN, saved)


def _key_pressed() -> bool:
    """Whether a key has been hit — and if so, swallow what was typed.

    Swallowed on purpose: the keystroke that ended the entrance was aimed at
    the entrance, and letting it fall through would answer the menu question
    printed a moment later with a character nobody chose.
    """
    if sys.platform == "win32":  # pragma: no cover - exercised on the windows leg
        import msvcrt

        pressed = False
        while msvcrt.kbhit():
            msvcrt.getwch()
            pressed = True
        return pressed
    import select

    try:
        ready, _writable, _failed = select.select([sys.stdin], [], [], 0)
        if not ready:
            return False
        os.read(sys.stdin.fileno(), 4096)
    except (AttributeError, OSError, ValueError):
        return False
    return True
