"""Synthea end-to-end lane — the external-evidence pipeline test.

Every other C-CDA fixture in this repo was authored here, so ingest tests
could share blind spots with the parser. ``synthea_ccda_sample.xml`` was
generated by an INDEPENDENT tool (Synthea / MDHT CDA libraries); this test
drives that file through the FULL real pipeline — ingest → reconstruct (REAL
Chromium) → QA → archive — plus a C-CDA round-trip, so real-world-shaped CDA
is exercised in both directions.

Synthetic data only: Synthea's own statement is that "no individual-level data
was used in creating it" (fixture README + ``tools/phi_allowlist.txt``
provenance). The patient is "Darryl392 Gislason620".

Marked ``e2e``: the unit lanes never collect it, and it SKIPS cleanly (no
import crash) when Playwright/Chromium is unavailable.

Counts are pinned to what this exact fixture yields (observed, not guessed):
1 patient, 1 encounter, 20 observations, 1 condition, 1 immunization.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import anastomosis.sources.ccda  # noqa: F401 — registers the C-CDA adapter
from anastomosis.core.model import PatientRecord
from anastomosis.sources import detect_source, get_source

pytestmark = pytest.mark.e2e

pytest.importorskip("playwright", reason="Synthea e2e needs the render extra (playwright)")
pytest.importorskip("fitz", reason="Synthea e2e needs the render extra (PyMuPDF)")

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "synthea"
PATIENT_NAME = ("Darryl392", "Gislason620")  # synthetic Synthea name (allowlisted provenance)

# Pinned from the actual fixture (see module docstring).
EXPECTED_ENCOUNTERS = 1
EXPECTED_OBSERVATIONS = 20
EXPECTED_CONDITIONS = 1
EXPECTED_IMMUNIZATIONS = 1


def _chromium_or_skip() -> None:
    from playwright.sync_api import sync_playwright

    try:
        with sync_playwright() as pw:
            pw.chromium.launch().close()
    except Exception as exc:  # browser not fetched / cannot launch
        pytest.skip(
            f"Chromium unavailable ({type(exc).__name__}); run 'playwright install chromium'"
        )


@pytest.fixture(scope="module")
def records() -> list[PatientRecord]:
    return list(get_source("ccda").load(FIXTURE))


def test_ingest_pins_synthea_counts(records: list[PatientRecord]) -> None:
    # Auto-detection identifies it as C-CDA (no --source needed).
    detected = detect_source(FIXTURE)
    assert detected is not None and detected.name == "ccda"

    assert len(records) == 1, "the fixture is a single ClinicalDocument -> one patient"
    record = records[0]
    assert (record.patient.given_name, record.patient.family_name) == PATIENT_NAME
    assert len(record.encounters) == EXPECTED_ENCOUNTERS
    assert len(record.observations) == EXPECTED_OBSERVATIONS
    assert len(record.conditions) == EXPECTED_CONDITIONS
    assert len(record.immunizations) == EXPECTED_IMMUNIZATIONS


def test_full_pipeline_reconstruct_qa_archive(records: list[PatientRecord], tmp_path: Path) -> None:
    _chromium_or_skip()
    from anastomosis.deliver.archive import ArchiveDeliverer
    from anastomosis.qa import Verdict, run_qa
    from anastomosis.reconstruct import discover_packs
    from anastomosis.reconstruct.chromium import ChromiumRenderer
    from anastomosis.reconstruct.engine import ReconstructionEngine

    # --- reconstruct (REAL Chromium through generic_soap) -------------------
    status = discover_packs()["generic_soap"]
    assert status.pack is not None, status.diagnosis
    pack = status.pack
    manifest = pack.manifest
    margins = {
        "top": manifest.page.margin_top,
        "right": manifest.page.margin_right,
        "bottom": manifest.page.margin_bottom,
        "left": manifest.page.margin_left,
    }
    out = tmp_path / "charts"
    engine = ReconstructionEngine(
        pack,
        lambda: ChromiumRenderer(page_size=manifest.page.size, margins=margins),
    )
    result = engine.run(records, out)
    assert len(result.rendered) >= 1, "at least one PDF must render"
    assert result.failed == [], f"no encounter may fail to render: {result.failed}"
    pdfs = list(out.glob("*.pdf"))
    assert len(pdfs) >= 1
    assert all(p.read_bytes().startswith(b"%PDF") for p in pdfs)

    # --- QA on the rendered output ------------------------------------------
    lookup = {(r.patient.id, e.id): (e, r) for r in records for e in r.encounters}
    report = run_qa(
        ((d.path, *lookup[d.patient_id, d.encounter_id]) for d in result.documents),
        section_flags=engine.section_flags,
        page_size=manifest.page.size,
    )
    # Hard invariant: zero FAILs. WARNs are allowed (Synthea is sparse), but
    # this exact fixture is stable at a clean full PASS.
    assert report.count(Verdict.FAIL) == 0, "QA must never FAIL on the Synthea chart"
    assert len(report.documents) == len(result.documents)
    assert report.count(Verdict.PASS) == 1
    assert report.count(Verdict.WARN) == 0

    # --- archive delivery ---------------------------------------------------
    archive = tmp_path / "archive"
    arc_result = ArchiveDeliverer(generator="anastomosis synthea e2e").deliver(
        records, out, archive, qa_report=report
    )
    assert arc_result.patient_count == 1
    assert (archive / "index.html").is_file()
    assert (archive / "_PHI_WARNING_README.txt").is_file()  # secure_output_dir guarantee
    patient_dir = archive / "patients" / records[0].patient.id
    assert (patient_dir / "index.html").is_file()
    assert (patient_dir / "bundle.json").is_file()
    enc_pages = list((patient_dir / "encounters").glob("*.html"))
    assert enc_pages, "per-patient encounter HTML must exist"

    # No network references anywhere in the emitted archive (offline guarantee).
    forbidden = ("https://", "http://", "//cdn", 'src="//', "fonts.googleapis", "cdnjs")
    web_files = [p for pat in ("*.html", "*.css", "*.js") for p in archive.rglob(pat)]
    assert web_files, "archive emitted no web assets to scan"
    for asset in web_files:
        text = asset.read_text(encoding="utf-8")
        for needle in forbidden:
            assert needle not in text, f"{asset.relative_to(archive)} references {needle!r}"


def test_ccda_round_trip_reparses_cleanly(records: list[PatientRecord], tmp_path: Path) -> None:
    """build_ccd(parse(synthea)) re-parses cleanly: well-formed, same patient
    name — external data driven through BOTH directions."""
    from anastomosis.deliver.ccda_export import build_ccd
    from anastomosis.sources.ccda.parser import parse_document

    record = records[0]
    xml_bytes = build_ccd(record)
    assert xml_bytes.lstrip().startswith(b"<?xml") or xml_bytes.lstrip().startswith(b"<")

    rebuilt = tmp_path / "synthea_roundtrip.xml"
    rebuilt.write_bytes(xml_bytes)
    reparsed = parse_document(rebuilt)

    assert (reparsed.patient.given_name, reparsed.patient.family_name) == PATIENT_NAME
    # The re-exported document still carries clinical content (loud proof the
    # round-trip is not an empty shell).
    assert len(reparsed.conditions) >= EXPECTED_CONDITIONS
    assert len(reparsed.immunizations) >= EXPECTED_IMMUNIZATIONS
