"""Pack-from-samples layout learner — the analysis half.

Infers a chart layout's design system from N sample PDFs, deterministically
and fully offline: OCR observation (:mod:`.ocr`), page evidence and
adjudication (:mod:`.evidence`), text/vector extraction (:mod:`.extract`),
and the statistics aggregated into
:class:`~anastomosis.packgen.infer.PackAnalysis` (:mod:`.infer`) — the
contract :mod:`anastomosis.packgen.emit` builds the draft pack from.
PHI and evidence rules: RULES.md 5, 33, 34, 75."""

from __future__ import annotations

from .evidence import (
    AMBIGUOUS,
    EMPTY,
    IMAGE_ONLY,
    MIXED,
    MIXED_EVIDENCE,
    NATIVE_ONLY,
    PAGE_CLASSES,
    EvidenceConflict,
    LayoutEvidence,
    OcrRegionError,
    PageEvidence,
    observe_page,
)
from .extract import (
    OCR_SPAN_FONT,
    DocumentSample,
    DrawnRect,
    NoExtractableTextError,
    OcrRequiredError,
    Span,
    extract_document,
    extract_samples,
)
from .infer import (
    OCR_EVIDENCE_CAVEAT,
    ColorUsage,
    ColumnGrid,
    ColumnStart,
    DesignTokens,
    PackAnalysis,
    PageBreakStats,
    PageGeometry,
    SectionCandidate,
    TypeScale,
    TypeScaleLevel,
    analyze,
    infer_column_grid,
    infer_design_tokens,
    infer_page_breaks,
    infer_page_geometry,
    infer_section_taxonomy,
    infer_static_text,
    infer_type_scale,
)
from .ocr import (
    NATIVE_OR_SYNTHETIC,
    NATIVE_TEXT,
    OCR_OBSERVATION,
    PROVENANCES,
    TESSERACT_BACKEND_ID,
    OcrConfig,
    OcrEngineError,
    OcrPageResult,
    OcrToken,
    OcrUnavailableError,
    PageImage,
    TesseractWorker,
    discover_worker,
    find_tesseract,
)

__all__ = [
    "AMBIGUOUS",
    "EMPTY",
    "IMAGE_ONLY",
    "MIXED",
    "MIXED_EVIDENCE",
    "NATIVE_ONLY",
    "NATIVE_OR_SYNTHETIC",
    "NATIVE_TEXT",
    "OCR_EVIDENCE_CAVEAT",
    "OCR_OBSERVATION",
    "OCR_SPAN_FONT",
    "PAGE_CLASSES",
    "PROVENANCES",
    "TESSERACT_BACKEND_ID",
    "ColorUsage",
    "ColumnGrid",
    "ColumnStart",
    "DesignTokens",
    "DocumentSample",
    "DrawnRect",
    "EvidenceConflict",
    "LayoutEvidence",
    "NoExtractableTextError",
    "OcrConfig",
    "OcrEngineError",
    "OcrPageResult",
    "OcrRegionError",
    "OcrRequiredError",
    "OcrToken",
    "OcrUnavailableError",
    "PackAnalysis",
    "PageBreakStats",
    "PageEvidence",
    "PageGeometry",
    "PageImage",
    "SectionCandidate",
    "Span",
    "TesseractWorker",
    "TypeScale",
    "TypeScaleLevel",
    "analyze",
    "discover_worker",
    "extract_document",
    "extract_samples",
    "find_tesseract",
    "infer_column_grid",
    "infer_design_tokens",
    "infer_page_breaks",
    "infer_page_geometry",
    "infer_section_taxonomy",
    "infer_static_text",
    "infer_type_scale",
    "observe_page",
]
