"""The corpus has to be reproducible, PHI-free, and actually varied: a
generator that drifts, spans one corner of the shape space, or leaks a
real-looking identifier fails silently as evidence infrastructure.

The full 6,144-document reading is a documented command, not a CI job:

    python tools/ccda_corpus.py --ledger --count 6144 --seed 7"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from tools.ccda_corpus import (
    DOC_TYPES,
    PRIMARY_FLAGS,
    SECONDARY_FLAGS,
    SECTIONS,
    documents,
    shapes,
    write_corpus,
)

from anastomosis.core.ccda_codes import EXT_SECTION_ENTRIES
from anastomosis.core.conservation import ConservationError
from anastomosis.sources import get_source
from anastomosis.sources.ccda.ledger import (
    _NARRATIVE_CONTAINERS,
    Disposition,
    DocumentLedger,
    aggregate,
    document_ledger,
)
from anastomosis.sources.ccda.parser import parse_document

#: Big enough to span the shape space, small enough that the unit lane stays a
#: unit lane. The thousands-scale run is the documented command above.
SCALE = 240

_GUID_SHAPED = re.compile(r"\b[0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-")
_SSN = re.compile(r"\b(\d{3})-(\d{2})-(\d{4})\b")
_PHONE = re.compile(r"\b(\d{3})\)?(\d{3})-(\d{4})\b")
_EMAIL = re.compile(r"[\w.+-]+@([\w.-]+)")


@pytest.fixture(scope="module")
def corpus() -> list[tuple[str, bytes]]:
    return list(documents(SCALE, seed=7))


# --- reproducible ------------------------------------------------------------


def test_the_same_seed_and_count_produce_the_same_bytes() -> None:
    """Every reading this corpus supports is quoted with a command. If the
    command produced a different corpus each run, the reading would be a claim
    nobody else could check."""
    assert list(documents(48, seed=7)) == list(documents(48, seed=7))


def test_the_shape_is_the_index_and_the_seed_is_only_the_contents() -> None:
    """A prefix of the enumeration must be the SAME prefix at any seed, or "run
    the first 240" would mean a different 240 for whoever ran it."""
    left = [(name, shape) for (name, _), shape in zip(documents(48, 7), shapes(48), strict=True)]
    right = [(name, shape) for (name, _), shape in zip(documents(48, 11), shapes(48), strict=True)]
    assert left == right
    assert list(documents(48, 7)) != list(documents(48, 11))  # content did move


def test_the_enumeration_covers_every_type_against_every_combination() -> None:
    """6,144 documents are the full product, exactly once each — the claim the
    module docstring makes, pinned so a stride that lost its coprimality (and
    therefore half the space) cannot pass quietly."""
    full = len(DOC_TYPES) << len(PRIMARY_FLAGS)
    seen = {
        (doc_type.key, frozenset(flags & set(PRIMARY_FLAGS))) for _, doc_type, flags in shapes(full)
    }
    assert len(seen) == full


def test_a_few_hundred_documents_already_span_the_space(
    corpus: list[tuple[str, bytes]],
) -> None:
    """What CI runs has to be a spread, not the corner of the space where every
    flag happens to be off."""
    flags = [flags for _, _, flags in shapes(SCALE)]
    types = {doc_type.key for _, doc_type, _ in shapes(SCALE)}
    assert types == {doc_type.key for doc_type in DOC_TYPES}
    for flag in (*PRIMARY_FLAGS, *SECONDARY_FLAGS):
        assert any(flag in seen for seen in flags), f"{flag} never on"
        assert any(flag not in seen for seen in flags), f"{flag} never off"
    assert len(corpus) == SCALE


# --- synthetic ---------------------------------------------------------------


def test_every_identifier_it_emits_is_a_fixture_identifier(
    corpus: list[tuple[str, bytes]],
) -> None:
    """The repo's synthetic conventions, asserted on the generated bytes rather
    than trusted to the generator's source: ``feedface-`` ids, never-issued SSN
    areas, the 555 exchange, ``example.com``."""
    for _, xml in corpus:
        text = xml.decode("utf-16" if xml[:2] in (b"\xff\xfe", b"\xfe\xff") else "utf-8")
        assert all(guid.startswith("feedface-") for guid in _GUID_SHAPED.findall(text))
        for area, _group, _serial in _SSN.findall(text):
            assert int(area) >= 900, f"SSN area {area} is issuable"
        for _area, exchange, _line in _PHONE.findall(text):
            assert exchange == "555", f"phone exchange {exchange} is dialable"
        assert set(_EMAIL.findall(text)) <= {"example.com"}


def test_no_document_reuses_an_id_root(corpus: list[tuple[str, bytes]]) -> None:
    """The ledger can only attribute an object to the construct it came from
    when that construct's id occurs once, so a corpus that reused a root would
    be measuring its own laziness."""
    for _, xml in corpus:
        roots = re.findall(rb"<id root=\"(feedface-[^\"]+)\"", xml.replace(b"\x00", b""))
        assert len(roots) == len(set(roots))


# --- it produces C-CDA, not something shaped like it --------------------------


def test_the_adapter_detects_and_parses_the_whole_corpus(tmp_path, corpus) -> None:  # type: ignore[no-untyped-def]
    """Including the UTF-16 documents: a corpus the adapter's own sniff skips
    would be measured as a corpus of zero, cleanly."""
    written = write_corpus(tmp_path / "corpus", 48, seed=7)
    adapter = get_source("ccda")
    assert adapter.detect(tmp_path / "corpus")
    assert len(list(adapter.load(tmp_path / "corpus"))) == written


def test_the_sections_it_declares_are_the_sections_that_arrive(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """A generator that emitted a section the parser cannot even see would make
    the ledger's ``unsupported`` column meaningless."""
    path = tmp_path / "one.xml"
    _, xml = next(iter(documents(1, seed=7)))
    path.write_bytes(xml)
    record = parse_document(path)
    assert record.conditions and record.medications and record.observations


# --- the reading, at a bounded scale -----------------------------------------


@pytest.fixture(scope="module")
def scale_report(tmp_path_factory: pytest.TempPathFactory) -> dict[str, object]:
    directory = tmp_path_factory.mktemp("corpus")
    ledgers = []
    for name, xml in documents(SCALE, seed=7):
        path = directory / name
        path.write_bytes(xml)
        ledgers.append(document_ledger(path))
        path.unlink()
    return aggregate(ledgers).as_report()


def _row(report: dict[str, object], construct: str) -> dict[str, int]:
    constructs = report["constructs"]
    assert isinstance(constructs, list)
    totals: dict[str, int] = {}
    for entry in constructs:
        if entry["construct"] == construct:
            for name, count in entry["instances"].items():
                totals[name] = totals.get(name, 0) + count
    assert totals, f"no row for {construct}"
    return totals


def test_the_corpus_books_balance(scale_report: dict[str, object]) -> None:
    """Not a spot check: every construct and every entry in 240 documents ended
    in exactly one column, or ``aggregate`` would already have refused."""
    assert scale_report["documents"] == SCALE
    assert scale_report["constructs_offered"] > 0
    assert scale_report["entries_offered"] > 0


@pytest.mark.parametrize(
    "construct",
    [
        "participation:author",
        "participation:authenticator",
        "participation:custodian",
        "participation:dataEnterer",
        "participation:encompassingEncounter",
        "participation:informationRecipient",
        "participation:legalAuthenticator",
        "participation:participant",
        "participation:performer",
        "participation:serviceEvent",
    ],
)
def test_the_named_actors_now_reach_the_record_at_scale(
    scale_report: dict[str, object], construct: str
) -> None:
    """Every one of these actors reaches a canonical object the ledger can
    trace to its ``<id root>``, with nothing left unsupported. The two
    id-less constructs missing from this list are the next test's subject."""
    totals = _row(scale_report, construct)
    assert totals[Disposition.STRUCTURALLY_PARSED.value] > 0
    assert totals.get(Disposition.UNSUPPORTED.value, 0) == 0


@pytest.mark.parametrize(
    "construct", ["participation:assignedAuthoringDevice", "participation:informant"]
)
def test_an_actor_cda_gives_no_id_is_credited_on_what_it_states(
    scale_report: dict[str, object], construct: str
) -> None:
    """CDA gives ``Device``/``RelatedEntity`` no ``<id>`` at all, so they are
    credited on content evidence instead (the record states what the
    document stated) -- absent, ambiguous or differently-spelled content
    is still not evidence (test_ccda_ledger.py holds that)."""
    totals = _row(scale_report, construct)
    assert totals[Disposition.STRUCTURALLY_PARSED.value] > 0
    assert totals.get(Disposition.UNSUPPORTED.value, 0) == 0


def test_the_generating_system_and_the_informant_still_reach_the_record(
    corpus: list[tuple[str, bytes]], tmp_path_factory: pytest.TempPathFactory
) -> None:
    """What the ledger credits must actually be on the record: the
    authoring device arrives as its own practitioner, and an informant
    with only a relationship keeps it."""
    directory = tmp_path_factory.mktemp("actors")
    entities: set[str] = set()
    informants: set[str] = set()
    for name, xml in corpus:
        path = directory / name
        path.write_bytes(xml)
        for practitioner in parse_document(path).practitioners:
            role = practitioner.extensions.get("ccda:participation")
            entities.add(str(practitioner.extensions.get("ccda:entity")))
            if role == "informant":
                informants.add(str(practitioner.extensions.get("ccda:code")))
        path.unlink()
    assert "assignedAuthoringDevice" in entities
    assert informants == {"spouse"}


def test_an_unstructured_body_reaches_the_record(scale_report: dict[str, object]) -> None:
    """Measured at corpus scale, not one document: a carry that worked on
    the fixture but not on the whole document TYPE would show as a
    partial column, not a pass."""
    totals = _row(scale_report, "body:nonXMLBody")
    assert totals[Disposition.STRUCTURALLY_PARSED.value] > 0
    assert totals.get(Disposition.UNSUPPORTED.value, 0) == 0


def test_all_four_dispositions_are_reachable(
    scale_report: dict[str, object], tmp_path: Path
) -> None:
    """Three dispositions occur in vivo; ``unsupported`` is proved by taking
    a document's practitioners away, since the parser now parks every
    section's entries so nothing in this corpus reaches neither data nor
    bytes."""
    constructs = scale_report["constructs"]
    assert isinstance(constructs, list)
    seen: set[str] = set()
    for entry in constructs:
        seen |= {name for name, count in entry["instances"].items() if count}
        seen |= {name for name, count in entry["entries"].items() if count}
    assert seen == {
        Disposition.STRUCTURALLY_PARSED.value,
        Disposition.NARRATIVE_PRESERVED.value,
        Disposition.SOURCE_EMPTY.value,
    }

    name, xml = next(documents(1, seed=7))
    path = tmp_path / name
    path.write_bytes(xml)
    record = parse_document(path)
    assert record.practitioners, "the probe needs a document with participations"
    record.practitioners = []
    stripped = document_ledger(path, record)
    dropped = {
        disposition
        for row in stripped.rows
        for disposition, count in row.instances.items()
        if count
    }
    assert Disposition.UNSUPPORTED in dropped


def test_taking_the_parked_copies_away_can_only_worsen_the_reading(
    corpus: list[tuple[str, bytes]], tmp_path: Path
) -> None:
    """Contract: stripping parked entries can only make the reading WORSE or
    equal, never better, and at least one document must actually lose
    ``unsupported`` credit -- proving the copies are load-bearing, not
    merely that removing them never helps (an entry credited both by its
    parked copy and by a cited narrative cell may still hold on the other)."""
    depended = 0
    for name, xml in corpus[:32]:
        path = tmp_path / name
        path.write_bytes(xml)
        record = parse_document(path)
        parked = [key for key in record.patient.extensions if key.startswith(EXT_SECTION_ENTRIES)]
        if not parked:
            continue
        before = _unsupported_entries(document_ledger(path, record))
        for key in parked:
            del record.patient.extensions[key]
        after = _unsupported_entries(document_ledger(path, record))
        assert after >= before, (
            f"{name}: {before} entries read unsupported with the parked copies in the "
            f"record and only {after} with them gone, so removing a copy IMPROVED the "
            "reading — a credit that does not depend on what it claims to rest on"
        )
        depended += after > before
    assert depended, (
        "no document in the sample lost an entry to the unsupported column when its "
        "parked copies were removed, so nothing here shows the copies are what hold "
        "the credit up"
    )


def _unsupported_entries(ledger: DocumentLedger) -> int:
    """How many entries this reading counts lost, across every row."""
    return sum(row.entries.get(Disposition.UNSUPPORTED, 0) for row in ledger.rows)


def test_every_section_the_generator_knows_appears_in_the_reading(
    scale_report: dict[str, object],
) -> None:
    """A section spec nobody emits is a dimension the corpus claims and does not
    have."""
    constructs = scale_report["constructs"]
    assert isinstance(constructs, list)
    seen = {str(entry["construct"]) for entry in constructs}
    for spec in SECTIONS.values():
        assert f"section:{spec.loinc}" in seen


def test_a_document_the_ledger_cannot_account_for_refuses(tmp_path, monkeypatch) -> None:  # type: ignore[no-untyped-def]
    """The scale run's guarantee is only worth what its refusal is worth."""
    from anastomosis.sources.ccda import ledger as module

    path = tmp_path / "one.xml"
    path.write_bytes(next(iter(documents(1, seed=7)))[1])
    document_ledger(path)
    monkeypatch.setattr(module, "_sections", lambda root: [], raising=True)
    with pytest.raises(ConservationError):
        document_ledger(path)


# --- it emits C-CDA R2.1, not the shape we happen to tolerate ----------------

#: What each element the generator emits may contain, in the order CDA R2 fixes.
#:
#: An allowlist of what THIS generator produces, not a schema validator: every
#: row is a content model taken from the CDA R2 base schema (``POCD_MT000040``
#: and the v3 datatypes), trimmed to the children this corpus actually writes
#: plus the siblings that surround them, and kept in the schema's own order.
#: Two facts are checked against it — that an element is legal where it stands,
#: and that its children stand in the legal order — because both are ways a
#: generated document can stop being a document any exporter could have
#: produced, and #327 was one of each: an ``intendedRecipient`` playing an
#: ``assignedPerson`` (a name CDA gives that role no home for) and a
#: ``custodian`` written before the ``dataEnterer`` it must follow.
#:
#: The corpus is evidence, and evidence about a document that could not exist is
#: not evidence about this adapter. Reading the spec is how the first divergence
#: was found; this table is so the next one is a failing test instead.
#:
#: Rows are keyed by element name, and by ``parent/name`` for the three names
#: CDA reuses with different content — ``component``, ``participant`` and
#: ``informationRecipient`` each mean two or three different things. Narrative
#: (``<text>`` under a section) is StrucDoc rather than CDA and is not walked.
#: Written as space-separated names because the ORDER is the content of each
#: row: one name per line would bury it under a column of quotes.
_CONTENT_MODEL: dict[str, tuple[str, ...]] = {
    key: tuple(model.split())
    for key, model in {
        "ClinicalDocument": (
            "realmCode typeId templateId id code title effectiveTime confidentialityCode"
            " languageCode recordTarget author dataEnterer informant custodian"
            " informationRecipient legalAuthenticator authenticator participant"
            " documentationOf componentOf component"
        ),
        # --- the patient
        "recordTarget": "patientRole",
        "patientRole": "id addr telecom patient",
        "patient": "name administrativeGenderCode birthTime languageCommunication",
        "languageCommunication": "languageCode",
        "addr": "streetAddressLine city state postalCode",
        "name": "given family suffix",
        # --- who wrote it, who took part, who holds it
        "author": "time assignedAuthor",
        "assignedAuthor": (
            "id code addr telecom assignedPerson assignedAuthoringDevice representedOrganization"
        ),
        "assignedPerson": "name",
        "assignedAuthoringDevice": "manufacturerModelName softwareName",
        "representedOrganization": "id name telecom addr",
        "dataEnterer": "assignedEntity",
        "assignedEntity": "id code addr telecom assignedPerson representedOrganization",
        "informant": "assignedEntity relatedEntity",
        "relatedEntity": "code addr telecom effectiveTime relatedPerson",
        "custodian": "assignedCustodian",
        "assignedCustodian": "representedCustodianOrganization",
        "representedCustodianOrganization": "id name telecom addr",
        # An intendedRecipient plays an ``informationRecipient``. It has no
        # ``assignedPerson`` at all, which is what this row exists to say.
        "ClinicalDocument/informationRecipient": "intendedRecipient",
        "intendedRecipient": "id addr telecom informationRecipient receivedOrganization",
        "intendedRecipient/informationRecipient": "name",
        "legalAuthenticator": "time signatureCode assignedEntity",
        "authenticator": "time signatureCode assignedEntity",
        "ClinicalDocument/participant": "associatedEntity",
        "associatedEntity": "id code addr telecom associatedPerson scopingOrganization",
        # --- what it documents, and the visit it belongs to
        "documentationOf": "serviceEvent",
        "serviceEvent": "id code statusCode effectiveTime performer",
        "performer": "assignedEntity",
        "componentOf": "encompassingEncounter",
        "encompassingEncounter": "id code effectiveTime responsibleParty location",
        "responsibleParty": "assignedEntity",
        # --- the body
        "ClinicalDocument/component": "structuredBody nonXMLBody",
        "nonXMLBody": "text",
        "structuredBody": "component",
        "structuredBody/component": "section",
        "section": "templateId id code title text entry",
        "entry": "act encounter observation observationMedia organizer substanceAdministration",
        # The image a narrative <renderMultiMedia> names is a clinical
        # statement, which is why it sits in an <entry> and not in the prose.
        "observationMedia": "id value",
        # --- the clinical statements
        "act": (
            "templateId id code text statusCode effectiveTime author participant entryRelationship"
        ),
        "entryRelationship": "observation",
        "observation": (
            "templateId id code text statusCode effectiveTime value participant entryRelationship"
        ),
        "observation/participant": "participantRole",
        # A statement's own <text> is an ED, and the only thing in one here is
        # the pointer into the narrative.
        "observation/text": "reference",
        "participantRole": "id code addr telecom playingEntity",
        "playingEntity": "code quantity name",
        "substanceAdministration": (
            "templateId id code text statusCode effectiveTime routeCode approachSiteCode"
            " doseQuantity rateQuantity consumable"
        ),
        "consumable": "manufacturedProduct",
        "manufacturedProduct": "templateId manufacturedMaterial manufacturerOrganization",
        "manufacturedMaterial": "code name lotNumberText",
        "organizer": "templateId id code statusCode effectiveTime component",
        "organizer/component": "observation act organizer",
        "encounter": (
            "templateId id code text statusCode effectiveTime performer participant"
            " entryRelationship"
        ),
        # --- datatypes. A coded value carries its own words FIRST and its
        # translations last; an interval carries its bounds.
        "code": "originalText qualifier translation",
        "value": "originalText qualifier translation",
        "administrativeGenderCode": "originalText qualifier translation",
        "originalText": "reference",
        "effectiveTime": "low high center width",
    }.items()
}

#: StrucDoc, not CDA: a section's narrative has its own schema, and the table
#: above cannot hold it, because most StrucDoc content models are unordered
#: CHOICES. Judging a choice by position asserts something the schema does not
#: say, and a legal rearrangement would then read as a defect — so the
#: narrative gets its own two tables, and the walk changes vocabulary when it
#: crosses into one.
_NARRATIVE_ROOT = "section/text"

#: What may appear inside each narrative element, in any order. Rows only for
#: the elements the corpus actually gives children to, on the same discipline
#: the CDA table keeps: a row nothing exercises is a claim nothing checks.
_NARRATIVE_CHOICE: dict[str, tuple[str, ...]] = {
    key: tuple(model.split())
    for key, model in {
        "text": "content linkHtml sub sup br footnote renderMultiMedia paragraph list table",
        # StrucDoc.Paragraph is (caption?, choice*): a caption is legal only
        # FIRST, which a choice row cannot say. The corpus writes no caption in
        # a paragraph, so the row omits it rather than admit one anywhere.
        "paragraph": "content linkHtml sub sup br footnote renderMultiMedia",
        # StrucDoc.Content has no caption at all (NarrativeBlock.xsd).
        "content": "content linkHtml sub sup br footnote renderMultiMedia",
        "td": "content linkHtml sub sup br footnote renderMultiMedia paragraph list",
        # StrucDoc.Tr is an unbounded choice of th | td — no order.
        "tr": "th td",
    }.items()
}

#: And the ones that ARE sequences, judged by position like the CDA rows.
_NARRATIVE_SEQUENCE: dict[str, tuple[str, ...]] = {
    key: tuple(model.split())
    for key, model in {
        # col and colgroup are a choice in StrucDoc.Table and the corpus writes
        # neither; the row holds only what it can judge by position.
        "table": "caption thead tfoot tbody",
        "list": "caption item",
        "tbody": "tr",
    }.items()
}


def _model_key(parent_name: str, name: str) -> str:
    """The content-model row an element is judged against: qualified
    ``parent/name`` for the names CDA reuses differently (e.g.
    ``component`` under ``ClinicalDocument`` vs under ``organizer``),
    else the bare name."""
    qualified = f"{parent_name}/{name}"
    return qualified if qualified in _CONTENT_MODEL else name


def _check_conformance(  # type: ignore[no-untyped-def]
    element, parent_name: str, seen: set[str], *, narrative: bool = False
) -> None:
    from lxml import etree

    name = etree.QName(element).localname
    narrative = narrative or f"{parent_name}/{name}" == _NARRATIVE_ROOT
    children = [etree.QName(child).localname for child in element if isinstance(child.tag, str)]
    if children:
        _check_model(name, children, parent_name, seen, narrative=narrative)
    for child in element:
        if isinstance(child.tag, str):
            _check_conformance(child, name, seen, narrative=narrative)


def _check_model(
    name: str, children: list[str], parent_name: str, seen: set[str], *, narrative: bool
) -> None:
    """One element's children against its governing row: order is asserted
    only where the schema states a sequence, never for a StrucDoc choice."""
    if narrative:
        seen.add(f"text/{name}")
        if name in _NARRATIVE_CHOICE:
            for child in children:
                assert child in _NARRATIVE_CHOICE[name], (
                    f"<{child}> is not legal inside narrative <{name}>"
                )
            return
        key, model, where = name, _NARRATIVE_SEQUENCE.get(name), "StrucDoc"
    else:
        key = _model_key(parent_name, name)
        model, where = _CONTENT_MODEL.get(key), "CDA"
        seen.add(key)
    assert model is not None, f"{parent_name}/{name}: no allowlisted {where} content model"
    positions = []
    for child in children:
        assert child in model, f"<{child}> is not legal inside <{name}> ({key})"
        positions.append(model.index(child))
    assert positions == sorted(positions), (
        f"<{name}> ({key}) writes {children} — "
        f"{where} orders them {[c for c in model if c in children]}"
    )


def test_every_element_it_emits_is_legal_where_it_stands(
    corpus: list[tuple[str, bytes]],
) -> None:
    """The corpus must be documents that could exist: until #327 it wrote a
    shape (``intendedRecipient/assignedPerson``) C-CDA gives no home for,
    testing tolerance instead of conformance."""
    from lxml import etree

    seen: set[str] = set()
    for _, xml in corpus:
        _check_conformance(etree.fromstring(xml), "", seen)
    expected = set(_CONTENT_MODEL) | {
        f"text/{name}" for name in (*_NARRATIVE_CHOICE, *_NARRATIVE_SEQUENCE)
    }
    assert seen == expected, f"content models the corpus never exercises: {sorted(expected - seen)}"


def _dangling_under(node, declared: set[str]):  # type: ignore[no-untyped-def]
    """Every name pointed at beneath ``node`` that the document never declares.

    ``referencedObject`` is an ``xs:IDREFS`` and may carry several names
    separated by whitespace; a ``<reference value="#…">`` carries one.
    """
    for element in node.iter():
        for value in (element.get("referencedObject") or "").split():
            if value not in declared:
                yield element, value
        value = element.get("value") or ""
        if value.startswith("#") and value[1:] not in declared:
            yield element, value[1:]


def _why_it_may_dangle(missing: str, has_text: bool, names_in_text: set[str]) -> str | None:
    """The one reason a citation in a section is allowed to resolve to
    nothing: no narrative in the section at all, the narrative names
    another cell, or a second (non-resolving) name sits beside a
    resolving one."""
    if "-narr-" in missing and not has_text:
        return "no narrative at all"
    if "-narr-" in missing and any("-elsewhere-" in n for n in names_in_text):
        return "the narrative names another cell"
    if "-elsewhere-" in missing and any("-narr-" in n for n in names_in_text):
        return "a second name beside a resolving one"
    return None


def test_every_name_a_document_points_at_is_a_name_it_declares(
    corpus: list[tuple[str, bytes]],
) -> None:
    """Every ID reference must resolve to a declared ``ID`` -- an unresolved
    one is a document no exporter could have written, except the one
    deliberate, bounded exception ``_cited_dangling`` writes on purpose
    so the ledger's refusal has something to measure."""
    from lxml import etree

    v3 = "urn:hl7-org:v3"
    forgiven = {
        "no narrative at all": 0,
        "the narrative names another cell": 0,
        "a second name beside a resolving one": 0,
    }
    for name, xml in corpus:
        root = etree.fromstring(xml)
        declared = {value for node in root.iter() if (value := node.get("ID"))}
        # Keyed by path, never by ``id()``: an lxml proxy is not the same object
        # across two walks of the tree, so identity would call every citation
        # "outside any section" on the second pass.
        judged: set[tuple[str, str]] = set()
        for section in root.iter(f"{{{v3}}}section"):
            text = section.find(f"{{{v3}}}text")
            names_in_text = (
                {n.get("ID") for n in text.iter() if n.get("ID")} if text is not None else set()
            )
            for element, missing in _dangling_under(section, declared):
                judged.add((root.getroottree().getpath(element), missing))
                why = _why_it_may_dangle(missing, text is not None, names_in_text)
                assert why is not None, (
                    f"{name}: points at {missing!r}, which the document never declares, "
                    "from a section no arrangement lets dangle"
                )
                forgiven[why] += 1
        outside = [
            m
            for element, m in _dangling_under(root, declared)
            if (root.getroottree().getpath(element), m) not in judged
        ]
        assert not outside, f"{name}: points at {outside} from outside any section"
    assert all(forgiven.values()), (
        "an arrangement this test forgives was never generated, so the exception "
        f"forgives nothing real: {forgiven}"
    )


def test_it_writes_the_narrative_arrangements_the_ledger_argues_about(
    corpus: list[tuple[str, bytes]],
) -> None:
    """Contract: the corpus must write every containment shape the ledger's
    crediting rule argues about -- an unnamed cell under a named row, a name
    at two nesting levels over one set of words, a name on the arrangement
    itself (must not be credited), a cell rendering nothing, and an
    unresolvable citation -- or one shape would agree with any rule."""
    from lxml import etree

    v3 = "urn:hl7-org:v3"
    seen = {
        "a row named above an unnamed cell": 0,
        "a name at two levels over one set of words": 0,
        "a name on the arrangement itself": 0,
        "a cell that renders nothing": 0,
        "a citation that resolves to nothing": 0,
    }
    for _, xml in corpus:
        for section in etree.fromstring(xml).iter(f"{{{v3}}}section"):
            text = section.find(f"{{{v3}}}text")
            if text is None:
                continue
            named = [n for n in text.iter() if not callable(n.tag) and n.get("ID")]
            for node in named:
                local = etree.QName(node).localname
                # The cell must be UNNAMED, or a row over two named cells
                # (`_cited_row`) satisfies a counter written for `_cited_nested`.
                if local == "tr" and any(
                    td.get("ID") is None for td in node.findall(f"{{{v3}}}td")
                ):
                    seen["a row named above an unnamed cell"] += 1
                if local in _NARRATIVE_CONTAINERS:
                    seen["a name on the arrangement itself"] += 1
                if node.find(f"{{{v3}}}renderMultiMedia") is not None:
                    seen["a cell that renders nothing"] += 1
                # Two names with an UNNAMED element between them — a named
                # child of a named parent (`_cited_row` again) is the shape at
                # which nearest-enclosing and outermost coincide and the
                # containment rule cannot be told from its neighbour.
                if any(
                    node in other.iterancestors() and other.getparent() is not node
                    for other in named
                ):
                    seen["a name at two levels over one set of words"] += 1
            defined = {node.get("ID") for node in named}
            for entry in section.findall(f"{{{v3}}}entry"):
                for reference in entry.iter(f"{{{v3}}}reference"):
                    value = (reference.get("value") or "").lstrip("#")
                    if value and value not in defined:
                        seen["a citation that resolves to nothing"] += 1

    missing = sorted(shape for shape, count in seen.items() if not count)
    assert not missing, f"the corpus never writes: {missing}"


def test_an_entry_with_no_structured_home_is_the_one_that_cites(
    corpus: list[tuple[str, bytes]],
) -> None:
    """A parsed entry's evidence is its own object and never spends a cell:
    at least one corpus citation must sit on an entry outside the
    adapter's structured dispatch, or the narrative-credit rule is
    generated and never exercised."""
    from lxml import etree

    v3 = "urn:hl7-org:v3"
    unstructured_cites = 0
    for _, xml in corpus:
        for section in etree.fromstring(xml).iter(f"{{{v3}}}section"):
            for entry in section.findall(f"{{{v3}}}entry"):
                # An <observation> carrying no templateId at all: nothing about
                # it is malformed and this adapter has no dispatch for it, which
                # is what makes it the entry that has to ask the narrative.
                observation = entry.find(f"{{{v3}}}observation")
                if observation is None or observation.find(f"{{{v3}}}templateId") is not None:
                    continue
                if next(entry.iter(f"{{{v3}}}reference"), None) is not None:
                    unstructured_cites += 1
    assert unstructured_cites, (
        "no entry outside this adapter's structured dispatch cites the narrative, "
        "so nothing in the corpus exercises the narrative-credit rule"
    )
