"""The corpus has to be reproducible, PHI-free, and actually varied.

A generator is evidence infrastructure, so its failure modes are quiet ones: a
corpus that drifts between runs makes every reading unarguable, a corpus that
only spans one corner of the shape space reports a clean ledger by omission, and
a corpus that grows a real-looking identifier puts PHI-shaped data in CI. Each
of those is tested here, and the scale test at the bottom is the one that
actually runs the instrument over a few hundred documents.

The full 6,144-document reading is a documented command, not a CI job:

    python tools/ccda_corpus.py --ledger --count 6144 --seed 7
"""

from __future__ import annotations

import re

import pytest
from tools.ccda_corpus import (
    DOC_TYPES,
    PRIMARY_FLAGS,
    SECONDARY_FLAGS,
    SECTIONS,
    documents,
    shapes,
    write_corpus,
)

from anastomosis.core.conservation import ConservationError
from anastomosis.sources import get_source
from anastomosis.sources.ccda.ledger import Disposition, aggregate, document_ledger
from anastomosis.sources.ccda.parser import parse_document

#: Big enough to span the shape space, small enough that the unit lane stays a
#: unit lane. The thousands-scale run is the documented command above.
SCALE = 240

_GUID_SHAPED = re.compile(r"\b[0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-")
_SSN = re.compile(r"\b(\d{3})-(\d{2})-(\d{4})\b")
_PHONE = re.compile(r"\b(\d{3})\)?(\d{3})-(\d{4})\b")
_EMAIL = re.compile(r"[\w.+-]+@([\w.-]+)")


@pytest.fixture(scope="module")
def corpus() -> list[tuple[str, bytes]]:
    return list(documents(SCALE, seed=7))


# --- reproducible ------------------------------------------------------------


def test_the_same_seed_and_count_produce_the_same_bytes() -> None:
    """Every reading this corpus supports is quoted with a command. If the
    command produced a different corpus each run, the reading would be a claim
    nobody else could check."""
    assert list(documents(48, seed=7)) == list(documents(48, seed=7))


def test_the_shape_is_the_index_and_the_seed_is_only_the_contents() -> None:
    """A prefix of the enumeration must be the SAME prefix at any seed, or "run
    the first 240" would mean a different 240 for whoever ran it."""
    left = [(name, shape) for (name, _), shape in zip(documents(48, 7), shapes(48), strict=True)]
    right = [(name, shape) for (name, _), shape in zip(documents(48, 11), shapes(48), strict=True)]
    assert left == right
    assert list(documents(48, 7)) != list(documents(48, 11))  # content did move


def test_the_enumeration_covers_every_type_against_every_combination() -> None:
    """6,144 documents are the full product, exactly once each — the claim the
    module docstring makes, pinned so a stride that lost its coprimality (and
    therefore half the space) cannot pass quietly."""
    full = len(DOC_TYPES) << len(PRIMARY_FLAGS)
    seen = {
        (doc_type.key, frozenset(flags & set(PRIMARY_FLAGS))) for _, doc_type, flags in shapes(full)
    }
    assert len(seen) == full


def test_a_few_hundred_documents_already_span_the_space(
    corpus: list[tuple[str, bytes]],
) -> None:
    """What CI runs has to be a spread, not the corner of the space where every
    flag happens to be off."""
    flags = [flags for _, _, flags in shapes(SCALE)]
    types = {doc_type.key for _, doc_type, _ in shapes(SCALE)}
    assert types == {doc_type.key for doc_type in DOC_TYPES}
    for flag in (*PRIMARY_FLAGS, *SECONDARY_FLAGS):
        assert any(flag in seen for seen in flags), f"{flag} never on"
        assert any(flag not in seen for seen in flags), f"{flag} never off"
    assert len(corpus) == SCALE


# --- synthetic ---------------------------------------------------------------


def test_every_identifier_it_emits_is_a_fixture_identifier(
    corpus: list[tuple[str, bytes]],
) -> None:
    """The repo's synthetic conventions, asserted on the generated bytes rather
    than trusted to the generator's source: ``feedface-`` ids, never-issued SSN
    areas, the 555 exchange, ``example.com``."""
    for _, xml in corpus:
        text = xml.decode("utf-16" if xml[:2] in (b"\xff\xfe", b"\xfe\xff") else "utf-8")
        assert all(guid.startswith("feedface-") for guid in _GUID_SHAPED.findall(text))
        for area, _group, _serial in _SSN.findall(text):
            assert int(area) >= 900, f"SSN area {area} is issuable"
        for _area, exchange, _line in _PHONE.findall(text):
            assert exchange == "555", f"phone exchange {exchange} is dialable"
        assert set(_EMAIL.findall(text)) <= {"example.com"}


def test_no_document_reuses_an_id_root(corpus: list[tuple[str, bytes]]) -> None:
    """The ledger can only attribute an object to the construct it came from
    when that construct's id occurs once, so a corpus that reused a root would
    be measuring its own laziness."""
    for _, xml in corpus:
        roots = re.findall(rb"<id root=\"(feedface-[^\"]+)\"", xml.replace(b"\x00", b""))
        assert len(roots) == len(set(roots))


# --- it produces C-CDA, not something shaped like it --------------------------


def test_the_adapter_detects_and_parses_the_whole_corpus(tmp_path, corpus) -> None:  # type: ignore[no-untyped-def]
    """Including the UTF-16 documents: a corpus the adapter's own sniff skips
    would be measured as a corpus of zero, cleanly."""
    written = write_corpus(tmp_path / "corpus", 48, seed=7)
    adapter = get_source("ccda")
    assert adapter.detect(tmp_path / "corpus")
    assert len(list(adapter.load(tmp_path / "corpus"))) == written


def test_the_sections_it_declares_are_the_sections_that_arrive(tmp_path) -> None:  # type: ignore[no-untyped-def]
    """A generator that emitted a section the parser cannot even see would make
    the ledger's ``unsupported`` column meaningless."""
    path = tmp_path / "one.xml"
    _, xml = next(iter(documents(1, seed=7)))
    path.write_bytes(xml)
    record = parse_document(path)
    assert record.conditions and record.medications and record.observations


# --- the reading, at a bounded scale -----------------------------------------


@pytest.fixture(scope="module")
def scale_report(tmp_path_factory: pytest.TempPathFactory) -> dict[str, object]:
    directory = tmp_path_factory.mktemp("corpus")
    ledgers = []
    for name, xml in documents(SCALE, seed=7):
        path = directory / name
        path.write_bytes(xml)
        ledgers.append(document_ledger(path))
        path.unlink()
    return aggregate(ledgers).as_report()


def _row(report: dict[str, object], construct: str) -> dict[str, int]:
    constructs = report["constructs"]
    assert isinstance(constructs, list)
    totals: dict[str, int] = {}
    for entry in constructs:
        if entry["construct"] == construct:
            for name, count in entry["instances"].items():
                totals[name] = totals.get(name, 0) + count
    assert totals, f"no row for {construct}"
    return totals


def test_the_corpus_books_balance(scale_report: dict[str, object]) -> None:
    """Not a spot check: every construct and every entry in 240 documents ended
    in exactly one column, or ``aggregate`` would already have refused."""
    assert scale_report["documents"] == SCALE
    assert scale_report["constructs_offered"] > 0
    assert scale_report["entries_offered"] > 0


@pytest.mark.parametrize(
    "construct",
    [
        "participation:author",
        "participation:custodian",
        "participation:performer",
        "participation:assignedAuthoringDevice",
        "participation:informant",
        "participation:legalAuthenticator",
        "participation:serviceEvent",
        "participation:encompassingEncounter",
        "body:nonXMLBody",
    ],
)
def test_the_named_actors_reach_nothing_at_scale(
    scale_report: dict[str, object], construct: str
) -> None:
    """The 2,103-document finding, reproduced on documents anyone can generate:
    every one of these is offered by the corpus, and not one becomes a canonical
    object. This test is expected to CHANGE when the extraction lands — that is
    what makes it the measurement rather than the fix."""
    totals = _row(scale_report, construct)
    assert totals[Disposition.UNSUPPORTED.value] > 0
    assert totals.get(Disposition.STRUCTURALLY_PARSED.value, 0) == 0


def test_all_four_dispositions_actually_occur(scale_report: dict[str, object]) -> None:
    """A corpus that never produces one of the four cannot tell whether the
    ledger can produce it either."""
    constructs = scale_report["constructs"]
    assert isinstance(constructs, list)
    seen: set[str] = set()
    for entry in constructs:
        seen |= {name for name, count in entry["instances"].items() if count}
        seen |= {name for name, count in entry["entries"].items() if count}
    assert seen == {disposition.value for disposition in Disposition}


def test_every_section_the_generator_knows_appears_in_the_reading(
    scale_report: dict[str, object],
) -> None:
    """A section spec nobody emits is a dimension the corpus claims and does not
    have."""
    constructs = scale_report["constructs"]
    assert isinstance(constructs, list)
    seen = {str(entry["construct"]) for entry in constructs}
    for spec in SECTIONS.values():
        assert f"section:{spec.loinc}" in seen


def test_a_document_the_ledger_cannot_account_for_refuses(tmp_path, monkeypatch) -> None:  # type: ignore[no-untyped-def]
    """The scale run's guarantee is only worth what its refusal is worth."""
    from anastomosis.sources.ccda import ledger as module

    path = tmp_path / "one.xml"
    path.write_bytes(next(iter(documents(1, seed=7)))[1])
    document_ledger(path)
    monkeypatch.setattr(module, "_sections", lambda root: [], raising=True)
    with pytest.raises(ConservationError):
        document_ledger(path)
